scrape_configs:

  - job_name: docker

    dockerswarm_sd_configs:
      - host: http://prometheus-service-discovery.internal:9093
        role: nodes
        filters:
          - name: id
            values: [ '{{.Node.ID}}' ]

    relabel_configs:

      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_id
        target_label: __address__
        replacement: host.docker.internal:9323

      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: instance
        replacement: $1:9323

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
      - action: labelmap
        regex: __meta_dockerswarm_(node_(?:id|hostname))
      - action: labeldrop
        regex: dockerswarm_node_(label_.+)
