# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Docker Swarm Nodes
# https://docs.docker.com/config/daemon/prometheus/
# 
# The Docker Engine metrics are required to be configured in the daemon.json file for Prometheus to scrape them.
# This configuration also includes a job to scrape the Node Exporter metrics that run on each node.
scrape_configs:
  - job_name: promstack/node-exporter

    dockerswarm_sd_configs:
      - host: http://prometheus-service-discovery.internal:9093
        role: nodes
        filters:
          - name: id
            values: [ '{{.Node.ID}}' ]

    relabel_configs:
      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_id
        target_label: __address__
        replacement: replica-$1.node-exporter.internal:9100

      # Set hostname as instance label
      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: instance
        replacement: $1:9100

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
      - action: labeldrop
        regex: dockerswarm_node_(label_.+)
      - action: labelmap
        regex: __meta_dockerswarm_(node_(?:id|hostname))

      # Set node_name label to node hostname
      # This is useful for providing compatibility with the swarmprom dashboards
      - source_labels:
          - __meta_dockerswarm_node_hostname
        target_label: node_name
