services:
  blackbox-exporter:
    configs:
    - source: prometheus-blackbox-exporter
    deploy:
      replicas: 1
      labels:
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.role: blackbox-exporter
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      resources:
        limits:
          memory: "134217728"
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 15
        window: 15s
      placement:
        max_replicas_per_node: 1
    hostname: replica-{{.Task.Slot}}.blackbox-exporter.internal
    image: docker.io/prom/blackbox-exporter:v0.25.0
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      prometheus_gwnetwork:
        aliases:
        - blackbox-exporter.internal
        - blackbox-exporter.svc.cluster.local
      public:
        aliases:
        - blackbox-exporter.svc.cluster.local
    ports:
    - mode: ingress
      target: 9115
      protocol: tcp
networks:
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
  public:
    name: public
    external: true
configs:
  prometheus-blackbox-exporter:
    name: prometheus-blackbox-exporter-v1
    file: ./prometheus/blackbox-exporter.yml
    labels:
      io.prometheus.scrape_config: "true"
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-exporter-resources-constraints:
  limits:
    memory: 128M
