# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Docker Swarm Nodes
# 
# The Docker Engine metrics are required to be configured in the daemon.json file for Prometheus to scrape them.
# This configuration also includes a job to scrape the Node Exporter metrics that run on each node.
scrape_configs:
  - job_name: prometheus-federated

    honor_labels: true
    metrics_path: /federate

    params:
      'match[]':
        - '{job="docker"}'
        - '{job="cadvisor"}'
        - '{job="node_exporter"}'
        - '{job="prometheus"}'

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes

    relabel_configs:
      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_id
        target_label: __address__
        replacement: replica-$1.prometheus-agent.internal:9090

      - source_labels:
        - __meta_dockerswarm_node_address
        - __address__
        target_label: instance
        regex: (.*);.*:(.*)
        replacement: $1:$2

      # The scrape_instance is temporary and will be removed in the metric_relabel_configs
      - source_labels:
        - instance
        target_label: scrape_instance

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
      - action: labeldrop
        regex: dockerswarm_node_(label_.+)
      - action: labelmap
        regex: __meta_dockerswarm_(node_(?:id|hostname))

    metric_relabel_configs:

      # Override the instance label with the scrape_instance label
      # And drop scrape_instance label
      - source_labels:
        - instance
        target_label: exported_instance
      - source_labels:
        - scrape_instance
        target_label: instance
      - action: labeldrop
        regex: scrape_instance
