# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Blackbox exporter
# https://github.com/prometheus/blackbox_exporter
#
scrape_configs:

  - job_name: promstack/blackbox-exporter

    honor_labels: true

    dns_sd_configs:
      - names:
          - tasks.blackbox-exporter.internal
        type: A
        port: 9115
        refresh_interval: "30s"
