services:
  prometheus-agent:
    command:
    - --agent
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.agent.path=/prometheus
    - --storage.agent.retention.min-time=1d
    - --storage.agent.retention.max-time=15d
    - --web.page-title=Promstack Prometheus Agent - Server
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --log.level=info
    configs:
    - source: prometheus-agent.yml.tmpl
      target: /etc/prometheus/prometheus.yml
    deploy:
      mode: global
      labels:
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.role: prometheus-agent
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      resources:
        limits:
          memory: "1073741824"
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 15
        window: 15s
    environment:
      DOCKERSWARM_NODE_HOSTNAME: '{{.Node.Hostname}}'
      DOCKERSWARM_NODE_ID: '{{.Node.ID}}'
      PROMETHEUS_AGENT_CLUSTER_REPLICA: '{{ index .Service.Labels "com.docker.stack.namespace"}}'
    extra_hosts:
    - host.docker.internal:host-gateway
    hostname: replica-{{.Task.Slot}}.prometheus-agent.internal
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO - --tries=1 --spider http://127.0.0.1:9090/-/healthy || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    image: docker.io/prom/prometheus:v3.0.0
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      prometheus_gwnetwork: null
    ports:
    - mode: host
      target: 9090
      published: 19090
    user: "0:0"
networks:
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
volumes:
  prometheus-agent-data: {}
configs:
  prometheus-agent.yml.tmpl:
    name: prometheus-agent.yml.tmpl-v1
    file: ./configs/prometheus.yml.tmpl
    template_driver: golang
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-deploy:
  mode: global
  resources:
    limits:
      memory: 1G
x-healthcheck:
  interval: 30s
  retries: 3
  start_period: 30s
  timeout: 10s
