{
 "title": "Promstack - DockerSwarm Services Endpoints",
 "description": "Docker Swarm Services Endpoints prober with Blackbox exporter",
 "tags": [
  "promstack",
  "dockerswarm-services",
  "blackbox"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(probe_success{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "TCP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", module=~\"tcp_connect\"}"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\", module=~\"tcp_connect\"}[1m])"
    }
   ]
  },
  {
   "title": "TCP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\", module=~\"tcp_connect\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP Probe Phases Duration",
     "type": "timeseries",
     "description": "Duration of tcp request by phase, summed over all redirects",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_duration_seconds{job=~\"$job\", instance=~\"$instance\", module=~\"tcp_connect\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}