{
 "title": "Promstack - Docker Stack",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_tasks_state,namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(container_tasks_state{namespace=~\"$namespace\"},dockerswarm_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", dockerswarm_service_name=~\"$service\"}[1m])) by (dockerswarm_service_name) * 100 ",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", dockerswarm_service_name=~\"$service\"}) by (dockerswarm_service_name) ",
     "legendFormat": "Used {{dockerswarm_service_name}}"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "service" },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_tasks_state{state=\"running\", dockerswarm_service_name=\"$service\"}) by (dockerswarm_service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", dockerswarm_service_name=~\"$service\"}[1m])) by (task) * 100 ",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", dockerswarm_service_name=~\"$service\"}) by (task) ",
     "legendFormat": "Used {{task}}"
    }
   ]
  },
  {
   "title": "Memory cached by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{namespace=~\"$namespace\", dockerswarm_service_name=~\"$service\"}) by (task) ",
     "legendFormat": "Cached {{task}}"
    }
   ]
  }
 ]
}