# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-healthcheck: &x-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 30s

x-grafana-deploy: &x-grafana-deploy
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.role == manager

x-grafana-provider-deploy: &x-grafana-provider-deploy
  mode: global
  placement:
    constraints:
      - node.labels.services.promstack_grafana == true

x-grafana-server-deploy: &x-grafana-server-deploy
  mode: global
  placement:
    constraints:
      # - node.labels.services.grafana_provisioning_config_reloader == true
      # - node.labels.services.promstack_grafana_dashboard_provider == true
      - node.labels.services.promstack_grafana_provisioning_alerting_provider == true
      - node.labels.services.promstack_grafana_provisioning_dashboard_provider == true
      - node.labels.services.promstack_grafana_provisioning_datasource_provider == true

x-grafana-reloader-deploy: &x-grafana-reloader-deploy
  mode: global
  placement:
    constraints:
      - node.labels.services.promstack_grafana_server == true

x-grafana-provider-resources-constraints: &x-grafana-provider-resources-constraints
  limits:
    memory: 64M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Grafana Dashboard
  # https://github.com/grafana/grafana
  # ====================================================

  grafana:
    image: busybox:latest
    command: sleep infinity
    deploy: *x-grafana-deploy

  grafana-server:
    image: ${PROMSTACK_GRAFANA_VERSION}
    entrypoint: ["/docker-entrypoint-shim.sh"]
    environment:
      # Default admin credentials
      GF_SECURITY_ADMIN_USER: $${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: $${GF_SECURITY_ADMIN_PASSWORD}
      # Server config
      GF_SERVER_PROTOCOL: $${GF_SERVER_PROTOCOL}
      GF_SERVER_DOMAIN: $${GF_SERVER_DOMAIN}
      GF_SERVER_ROOT_URL: $${GF_SERVER_ROOT_URL}
      # Snapshot service config
      GF_SNAPSHOTS_EXTERNAL_SNAPSHOT_URL: $${GF_SNAPSHOTS_EXTERNAL_SNAPSHOT_URL}
      GF_SNAPSHOTS_EXTERNAL_SNAPSHOT_NAME: $${GF_SNAPSHOTS_EXTERNAL_SNAPSHOT_NAME}
      # SQlite database mode
      GF_DATABASE_WAL: "true"
      GF_DATABASE_CACHE_MODE: "shared"
      # SMTP configuration placeholders
      GF_SMTP_ENABLED:
      GF_SMTP_HOST:
      GF_SMTP_USER:
      GF_SMTP_PASSWORD:
      GF_SMTP_FROM_ADDRESS:
      GF_SMTP_FROM_NAME:
      GF_SMTP_SKIP_VERIFY:
      # docker-entrypoint-shim.sh
      GRAFANA_UNIFIED_ALERTING_INTERFACE: eth2
    networks:
      prometheus: # eth1
      grafana: # eth2
        aliases:
          - grafana.internal
      public: # eth3
        aliases:
          - grafana.svc.cluster.local
      prometheus_gwnetwork:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    hostname: replica-{{.Node.ID}}.grafana.internal
    configs:
      - source: gf-server-entrypoint
        target: /docker-entrypoint-shim.sh
        mode: 0555
      - source: gf-provisioning-dashboards
        target: /etc/grafana/provisioning/dashboards/gf-provisioning-dashboards.yml
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana
      - type: volume
        source: grafana-logs
        target: /var/log/grafana
      - type: volume
        source: grafana-dashboards
        target: /etc/grafana/dashboards
      - type: volume
        source: grafana-provisioning-alerting
        target: /etc/grafana/provisioning/alerting
      - type: volume
        source: grafana-provisioning-dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: volume
        source: grafana-provisioning-datasources
        target: /etc/grafana/provisioning/datasources
    healthcheck:
      <<: *x-healthcheck
      test: wget -qO - --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1
    logging: *x-default-logging
    deploy:
      # <<: *x-deploy
      <<: *x-grafana-server-deploy
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: "grafana"
        io.prometheus.scrape_port: "3000"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2

  # ====================================================
  # Grafana provisioning config provider & reloader
  # Only 1 replica is needed for each
  # ====================================================
  
  grafana-provisioning-config-reloader:
    image: ${PROMSTACK_GRAFANA_CONFIG_RELOADER_VERSION}
    environment:
      GF_SERVER_DOMAIN: replica-{{.Node.ID}}.grafana.internal
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      # Default admin credentials
      GF_SECURITY_ADMIN_USER: $${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: $${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      grafana:
    volumes:
      - type: volume
        source: grafana-provisioning-config-reloader
        target: /data
      - type: volume
        source: grafana-provisioning-alerting
        target: /etc/grafana/provisioning/alerting
      - type: volume
        source: grafana-provisioning-dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: volume
        source: grafana-provisioning-datasources
        target: /etc/grafana/provisioning/datasources
        read_only: true
    logging: *x-default-logging
    deploy:
      <<: *x-grafana-reloader-deploy
      resources: *x-grafana-provider-resources-constraints
      restart_policy:
        condition: any
        # max_attempts: 15
        delay: 15s
        window: 10s
      rollback_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
        order: start-first
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
        order: start-first
    depends_on:
      - grafana
      - grafana-dashboard-provider
      - grafana-provisioning-dashboard-provider
      - grafana-provisioning-datasource-provider

  # Grafana dashboards provider
  grafana-dashboard-provider: &grafana-config-provider
    image: ${PROMSTACK_GRAFANA_CONFIG_PROVIDER_VERSION}
    command:
      - --output-ext=json
      - --output-dir=/grafana-dashboards.d
      - --prometheus-scrape-config-label=io.grafana.dashboard
    configs:
      - source: gf-dashboard-promstack-grafana-metrics
      - source: gf-dashboard-promstack-prometheus-stats
      - source: gf-dashboard-promstack-prometheus-stats-v2
      - source: gf-dashboard-promstack-dockerswarm-nodes
      # - source: gf-dashboard-promstack-dockerswarm-services-endpoints
      - source: gf-dashboard-promstack-dockerswarm-services
      - source: gf-dashboard-promstack-cadvisor
      - source: gf-dashboard-promstack-node-exporter
    volumes:
      - type: volume
        source: grafana-dashboards
        target: /grafana-dashboards.d
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    logging: *x-default-logging
    deploy:
      <<: *x-grafana-provider-deploy
      resources: *x-grafana-provider-resources-constraints
      restart_policy:
        condition: any
        # max_attempts: 15
        delay: 15s
        window: 10s
      rollback_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2

  # Grafana provisioning config for alerting, datasources and dashboards
  grafana-provisioning-alerting-provider:
    <<: *grafana-config-provider
    command:
      - --output-dir=/grafana-provisioning-alerting.d
      - --prometheus-scrape-config-label=io.grafana.provisioning.alerting
    volumes:
      - type: volume
        source: grafana-provisioning-alerting
        target: /grafana-provisioning-alerting.d
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

  grafana-provisioning-dashboard-provider:
    <<: *grafana-config-provider
    command:
      - --output-dir=/grafana-provisioning-dashboards.d
      - --prometheus-scrape-config-label=io.grafana.provisioning.dashboard
    volumes:
      - type: volume
        source: grafana-provisioning-dashboards
        target: /grafana-provisioning-dashboards.d
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

  grafana-provisioning-datasource-provider:
    <<: *grafana-config-provider
    command:
      - --output-dir=/grafana-provisioning-datasources.d
      - --prometheus-scrape-config-label=io.grafana.provisioning.datasource
    configs:
      - source: gf-provisioning-datasource-prometheus
    volumes:
      - type: volume
        source: grafana-provisioning-datasources
        target: /grafana-provisioning-datasources.d
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

volumes:
  grafana-data:
  grafana-logs:
  grafana-dashboards:
  grafana-provisioning-alerting:
  grafana-provisioning-dashboards:
  grafana-provisioning-datasources:
  grafana-provisioning-config-reloader:

networks:
  public:
    name: public
    external: true
  grafana:
    # Internal network for Grafana services
    attachable: true
  prometheus:
    name: prometheus
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true

configs:
  # Grafana entrypoint script
  gf-server-entrypoint:
    name: gf-server-entrypoint-v1
    file: ./grafana/docker-entrypoint-shim.sh

  # Grafana dashboards provisioning config
  gf-provisioning-dashboards:
    # Note: The dashboards provisioning config does not need to be labeled,
    #       instead we mount the file directly into the Grafana container.
    name: gf-provisioning-dashboards-v1
    file: ./grafana/provisioning/dashboards/grafana-dashboards.yml

  # Grafana datasources provisioning config
  gf-provisioning-datasource-prometheus:
    name: gf-provisioning-datasource-prometheus-v1
    file: ./grafana/provisioning/datasources/prometheus.yml
    labels:
      io.grafana.provisioning.datasource: "true"

  # Grafana & Prometheus dashboards
  gf-dashboard-promstack-grafana-metrics:
    name: gf-dashboard-promstack-grafana-metrics-v1
    file: ./grafana/dashboards/promstack-grafana-metrics.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-promstack-prometheus-stats:
    name: gf-dashboard-promstack-prometheus-stats-v1
    file: ./grafana/dashboards/promstack-prometheus-stats.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-promstack-prometheus-stats-v2:
    name: gf-dashboard-promstack-prometheus-stats-v2
    file: ./grafana/dashboards/promstack-prometheus-2-0-stats.json
    labels:
      io.grafana.dashboard: "true"

  # Docker Swarm specific dashboards
  gf-dashboard-promstack-dockerstack:
    name: gf-dashboard-promstack-dockerstack-v1
    file: ./grafana/dashboards/promstack-dockerstack.json
    labels:
      io.grafana.dashboard: "true"
  gf-dashboard-promstack-dockerswarm-nodes:
    name: gf-dashboard-promstack-dockerswarm-nodes-v1
    file: ./grafana/dashboards/promstack-dockerswarm-nodes.json
    labels:
      io.grafana.dashboard: "true"
  # gf-dashboard-promstack-dockerswarm-services-endpoints:
  #   name: gf-dashboard-promstack-dockerswarm-services-endpoints-v1
  #   file: ./grafana/dashboards/promstack-dockerswarm-services-endpoints.json
  #   labels:
  #     io.grafana.dashboard: "true"
  gf-dashboard-promstack-dockerswarm-services:
    name: gf-dashboard-promstack-dockerswarm-services-v1
    file: ./grafana/dashboards/promstack-dockerswarm-services.json
    labels:
      io.grafana.dashboard: "true"

  # cAdvisor
  gf-dashboard-promstack-cadvisor:
    name: gf-dashboard-promstack-cadvisor-v1
    file: ./grafana/dashboards/promstack-cadvisor.json
    labels:
      io.grafana.dashboard: "true"
  # Node Exporter
  gf-dashboard-promstack-node-exporter:
    name: gf-dashboard-promstack-node-exporter-v1
    file: ./grafana/dashboards/promstack-node-exporter.json
    labels:
      io.grafana.dashboard: "true"
