# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# # Scrape config for container metrics
# https://github.com/google/cadvisor
# 
scrape_configs:

  - job_name: promstack/cadvisor

    static_configs:
      - targets:
          - 'replica-{{.Task.Slot}}.cadvisor.internal:8080'

    metric_relabel_configs:
      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: container_label_com_(docker_.*)

      # Rename labels docker_swarm_(.+) to dockerswarm_$1
      # This is useful for compatibility with "dockerswarm-tasks.yml" relabeling
      - action: labelmap
        regex: container_label_com_docker_swarm_(.+)
        replacement: dockerswarm_$1
      - action: labeldrop
        regex: (^docker_swarm_.+)

      # ================================================================================
      # Docker Swarm compatible relabeling
      # - dockerswarm_task_name
      # ================================================================================

      # Set "task" label to "<service_name>.<task_slot>
      - source_labels:
        - dockerswarm_task_name
        target_label: task
        regex: (.+)\.(.+)\.(.+)
        replacement: $1.$2

      # ================================================================================
      # Kubernetes compatible relabeling
      # - namespace
      # - deployment
      # - pod
      # ================================================================================
      # # Set Kubernetes's Namespace with "com.docker.stack.namespace" label
      - source_labels:
        - container_label_com_docker_stack_namespace
        target_label: namespace

      # Set Kubernetes's Deployment with "com.docker.stack.namespace" label
      - source_labels:
        - container_label_com_docker_swarm_service_name
        target_label: deployment

      # Set Kubernetes's Pod Name with Docker Swarm's Service Name
      - source_labels:
        - dockerswarm_task_name
        target_label: pod
        regex: (.*)
