#!/usr/bin/env sh
# Copyright (c) Swarm Library Maintainers.
# SPDX-License-Identifier: MIT
set -e

get_addr () {
  local if_name=$1
  ip addr show dev $if_name | awk '/\s*inet\s/ { ip=gensub(/(.+)\/.+/, "\\1", "g", $2); print ip; exit }'
}

# Default credentials
export GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-"grafana"}
export GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-"grafana"}

# Unified Alerting
GRAFANA_UNIFIED_ALERTING_PORT=${GF_UNIFIED_ALERTING_PORT:-9094}
if [[ -n "${GRAFANA_UNIFIED_ALERTING_INTERFACE}" ]]; then
  export GRAFANA_UNIFIED_ALERTING_ADVERTISE_ADDRESS=$(get_addr $GRAFANA_UNIFIED_ALERTING_INTERFACE):${GRAFANA_UNIFIED_ALERTING_PORT}
  echo "Using $GRAFANA_UNIFIED_ALERTING_INTERFACE for GRAFANA_UNIFIED_ALERTING_ADVERTISE_ADDRESS: $GRAFANA_UNIFIED_ALERTING_ADVERTISE_ADDRESS"
fi
export GF_UNIFIED_ALERTING_ENABLED=${GF_UNIFIED_ALERTING_ENABLED:-"true"}
export GF_UNIFIED_ALERTING_HA_PEERS=${GF_UNIFIED_ALERTING_HA_PEERS:-"tasks.grafana:${GRAFANA_UNIFIED_ALERTING_PORT}"}
export GF_UNIFIED_ALERTING_HA_LISTEN_ADDRESS=${GF_UNIFIED_ALERTING_HA_LISTEN_ADDRESS:-":${GRAFANA_UNIFIED_ALERTING_PORT}"}
export GF_UNIFIED_ALERTING_HA_ADVERTISE_ADDRESS=${GRAFANA_UNIFIED_ALERTING_ADVERTISE_ADDRESS:-":${GRAFANA_UNIFIED_ALERTING_PORT}"}
export GF_UNIFIED_ALERTING_HA_PEER_TIMEOUT=${GF_UNIFIED_ALERTING_HA_PEER_TIMEOUT:-"15s"}

# Set default values for Grafana environment variables
export GF_LOG_LEVEL=${GF_LOG_LEVEL:-"info"}
export GF_METRICS_ENABLED=${GF_METRICS_ENABLED:-"true"}
export GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP:-"false"}

# Disable all analytics and reporting
export GF_ANALYTICS_CHECK_FOR_UPDATES=${GF_ANALYTICS_CHECK_FOR_UPDATES:-"false"}
export GF_ANALYTICS_FEEDBACK_LINKS_ENABLED=${GF_ANALYTICS_FEEDBACK_LINKS_ENABLED:-"false"}
export GF_ANALYTICS_REPORTING_ENABLED=${GF_ANALYTICS_REPORTING_ENABLED:-"false"}
export GF_NEWS_NEWS_FEED_ENABLED=${GF_NEWS_NEWS_FEED_ENABLED:-"false"}
export GF_SUPPORT_BUNDLES_ENABLED=${GF_SUPPORT_BUNDLES_ENABLED:-"false"}

# Enable feature toggles
export GF_FEATURE_TOGGLES_ENABLE=${GF_FEATURE_TOGGLES_ENABLE:-"true"}

echo "==> Grafana started! Log data will be stream in below:"
exec /run.sh "$@"
