services:
  pushgateway:
    configs:
    - source: prometheus-pushgateway
    deploy:
      replicas: 1
      labels:
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.role: pushgateway
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      resources:
        limits:
          memory: "134217728"
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 15
        window: 15s
      placement:
        max_replicas_per_node: 1
    hostname: replica-{{.Task.Slot}}.pushgateway.internal
    image: docker.io/prom/pushgateway:v1.10.0
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      prometheus:
        aliases:
        - pushgateway.svc.cluster.local
      prometheus_gwnetwork:
        aliases:
        - pushgateway.internal
        - pushgateway.svc.cluster.local
networks:
  prometheus:
    name: prometheus
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
configs:
  prometheus-pushgateway:
    name: prometheus-pushgateway-v1
    file: ./prometheus/pushgateway.yml
    labels:
      io.prometheus.scrape_config: "true"
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-exporter-resources-constraints:
  limits:
    memory: 128M
