# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M
  reservations:
    memory: 64M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Prometheus Pushgateway
  # https://github.com/prometheus/pushgateway
  # ====================================================

  pushgateway:
    image: prom/pushgateway:v1.9.0
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "pushgateway"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
    logging: *x-default-logging
    hostname: replica-{{.Task.Slot}}.pushgateway.local
    networks:
      prometheus_gwnetwork:
        aliases:
          - pushgateway.local
    configs:
      - source: prometheus-pushgateway

configs:
  prometheus-pushgateway:
    name: prometheus-pushgateway-v1
    file: ./prometheus/pushgateway.yml
    labels:
      - "io.prometheus.scrape_config=true"

networks:
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
