# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Prometheus Pushgateway
  # https://github.com/prometheus/pushgateway
  # ====================================================

  pushgateway:
    image: ${PROMSTACK_PUSHGATEWAY_VERSION}
    networks:
      prometheus:
        aliases:
          - pushgateway.svc.cluster.local
      prometheus_gwnetwork:
        aliases:
          - pushgateway.internal
          - pushgateway.svc.cluster.local
    hostname: replica-{{.Task.Slot}}.pushgateway.internal
    configs:
      - source: prometheus-pushgateway
    logging: *x-default-logging
    deploy:
      mode: global
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "pushgateway"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2

configs:
  prometheus-pushgateway:
    name: prometheus-pushgateway-v1
    file: ./prometheus/pushgateway.yml
    labels:
      io.prometheus.scrape_config: "true"

networks:
  prometheus:
    name: prometheus
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
