# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Prometheus Pushgateway
# https://github.com/prometheus/pushgateway
#
scrape_configs:

  - job_name: pushgateway

    honor_labels: true

    dns_sd_configs:
      - names:
          - tasks.pushgateway.internal
        type: A
        port: 9091
        refresh_interval: "30s"
