# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # cAdvisor
  # https://github.com/google/cadvisor
  # ====================================================

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    command: -docker_only
    deploy:
      mode: global
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "cadvisor"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
    logging: *x-default-logging
    hostname: replica-{{.Task.Slot}}.cadvisor.local
    # ports:
    #   - published: 8080
    #     target: 8080
    #     mode: host
    networks:
      prometheus_gwnetwork:
        aliases:
          - cadvisor.local
    configs:
      - source: prometheus-cadvisor
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      # If you are running Docker Desktop on macOS,
      # You'll need to comment out the following bind mounts
      # - type: bind
      #   source: /dev/disk
      #   target: /dev/disk
      #   read_only: true
      # - type: bind
      #   source: /dev/kmsg
      #   target: /dev/kmsg
      #   read_only: true

networks:
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true

configs:
  prometheus-cadvisor:
    name: prometheus-cadvisor-v1
    file: ./prometheus/cadvisor.yml
    labels:
      - "io.prometheus.scrape_config=true"
