services:
  prometheus-federated:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=15d
    - --web.page-title=Prometheus Server Federated - Promstack
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --log.level=info
    configs:
    - source: prometheus-federated-config-tmpl
      target: /etc/prometheus/prometheus.yml
    - source: prometheus-federated-cadvisor
      target: /etc/prometheus/scrape-configs/cadvisor.yml
    - source: prometheus-federated-docker
      target: /etc/prometheus/scrape-configs/docker.yml
    - source: prometheus-federated-dockerswarm-services
      target: /etc/prometheus/scrape-configs/dockerswarm-services.yml
    - source: prometheus-federated-node_exporter
      target: /etc/prometheus/scrape-configs/node_exporter.yml
    - source: prometheus-federated-prometheus
      target: /etc/prometheus/scrape-configs/prometheus.yml
    deploy:
      mode: global
      labels:
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.role: prometheus-federated
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      resources:
        limits:
          memory: "1073741824"
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 15
        window: 15s
    environment:
      DOCKERSWARM_NODE_HOSTNAME: '{{.Node.Hostname}}'
      DOCKERSWARM_NODE_ID: '{{.Node.ID}}'
      PROMETHEUS_AGENT_CLUSTER_REPLICA: '{{ index .Service.Labels "com.docker.stack.namespace"}}'
    extra_hosts:
    - host.docker.internal:host-gateway
    hostname: replica-{{.Task.Slot}}.federated.prometheus.internal
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO - --tries=1 --spider http://127.0.0.1:9090/-/healthy || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    image: docker.io/prom/prometheus:v3.0.0
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      prometheus_gwnetwork: null
    ports:
    - mode: host
      target: 9090
      published: 19090
    user: "0:0"
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    - type: volume
      source: prometheus-federated-data
      target: /prometheus
networks:
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
volumes:
  prometheus-federated-data: {}
configs:
  prometheus-federated-cadvisor:
    name: prometheus-federated-cadvisor-v1
    file: ./prometheus/scrape-configs/cadvisor.yml
    template_driver: golang
  prometheus-federated-config-tmpl:
    name: prometheus-federated-config-tmpl-v1
    file: ./prometheus/prometheus.yml.tmpl
    template_driver: golang
  prometheus-federated-docker:
    name: prometheus-federated-docker-v1
    file: ./prometheus/scrape-configs/docker.yml
  prometheus-federated-dockerswarm-services:
    name: prometheus-federated-dockerswarm-services-v1-2
    file: ./prometheus/scrape-configs/dockerswarm-services.yml
    template_driver: golang
  prometheus-federated-node_exporter:
    name: prometheus-federated-node_exporter-v1
    file: ./prometheus/scrape-configs/node_exporter.yml
    template_driver: golang
  prometheus-federated-prometheus:
    name: prometheus-federated-prometheus-v1
    file: ./prometheus/scrape-configs/prometheus.yml
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-deploy:
  mode: global
  resources:
    limits:
      memory: 1G
x-healthcheck:
  interval: 30s
  retries: 3
  start_period: 30s
  timeout: 10s
