services:
  node-exporter:
    command:
    - --path.rootfs=/rootfs
    - --collector.textfile.directory=/etc/node-exporter
    - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    - --no-collector.ipvs
    configs:
    - source: node-exporter-node-meta
      target: /etc/node-exporter/node_meta.prom
    deploy:
      mode: global
      labels:
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.role: node-exporter
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.2
      resources:
        limits:
          memory: "134217728"
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 15
        window: 15s
    hostname: replica-{{.Task.Slot}}.node-exporter.internal
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO - --tries=1 --spider http://127.0.0.1:9100 || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    image: docker.io/prom/node-exporter:v1.8.2
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      prometheus_gwnetwork: null
    ports:
    - mode: host
      target: 9100
      published: 19100
    volumes:
    - type: bind
      source: /
      target: /rootfs
      read_only: true
networks:
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
configs:
  node-exporter-node-meta:
    name: prometheus-node-exporter-node-meta-v1
    file: ./node_meta.prom
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-exporter-resources-constraints:
  limits:
    memory: 128M
x-healthcheck:
  interval: 30s
  retries: 3
  start_period: 30s
  timeout: 10s
