# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-healthcheck: &x-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 30s

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Node exporter
  # https://github.com/prometheus/node_exporter
  # ====================================================

  node-exporter:
    image: ${PROMSTACK_NODE_EXPORTER_VERSION}
    command:
      - --path.rootfs=/rootfs
      - --collector.textfile.directory=/etc/node-exporter
      # Due to interpolation the dolar sign must be escaped,
      # since it double dollar sign we need to escape it twice
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$$$|/)
      - --no-collector.ipvs
    ports:
      - published: 9100
        target: 9100
        mode: host
    networks:
      prometheus_gwnetwork:
        aliases:
          - node-exporter.internal
    hostname: "replica-{{.Task.Slot}}.node-exporter.internal"
    configs:
      - source: node-exporter-node-meta
        target: /etc/node-exporter/node_meta.prom
      - source: prometheus-node-exporter
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
    healthcheck:
      <<: *x-healthcheck
      test: wget -qO - --tries=1 --spider http://127.0.0.1:9100 || exit 1
    logging: *x-default-logging
    deploy:
      mode: global
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "node-exporter"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1

configs:
  # Node exporter textfile collector
  node-exporter-node-meta:
    name: node-exporter-node-meta-v1
    file: ./node_meta.prom

  # Prometheus node exporter scrape config
  prometheus-node-exporter:
    name: prometheus-node-exporter-v1
    file: ./prometheus/node_exporter.yml
    labels:
      - "io.prometheus.scrape_config=true"

networks:
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
